"""Seed a runnable demo: users, model registry, synthetic sample images, and a
few analysed cases across skin-tone groups so the fairness view is populated.

Everything here is synthetic. No real patient data is used or required.

    python -m app.seed              # seed the database and write samples/
    python -m app.seed --reset      # drop and recreate the schema first
"""

from __future__ import annotations

import argparse
import asyncio
import datetime as dt
from pathlib import Path

from sqlalchemy import select

from .analysis.modules_config import MODULES
from .analysis.pipeline import AnalysisJob, execute
from .config import settings
from .db import SessionLocal, engine
from .models import (Analysis, Base, Case, Image, Lesion, ModelRegistry,
                     Organisation, Patient, User)
from .sample_data import SAMPLES, png_bytes
from .security import hash_password
from .storage import build_key, get_storage
from .summary import build_summary

SAMPLES_DIR = Path(__file__).resolve().parent.parent / "samples"

# Demo patients spread across Monk Skin Tone bands so the stratified fairness
# view has more than one stratum. Pseudonymous codes only.
DEMO_PATIENTS = [
    ("DEMO-A1", 1985, "female", 2),
    ("DEMO-B2", 1972, "male", 5),
    ("DEMO-C3", 1990, "female", 8),
]


async def _ensure_org(session) -> Organisation:
    existing = (await session.execute(
        select(Organisation).where(Organisation.slug == "demo-clinic")
    )).scalar_one_or_none()
    if existing:
        return existing
    org = Organisation(name="QADAM Demo Clinic", slug="demo-clinic", country="AE")
    session.add(org)
    await session.flush()
    print(f"  organisation {org.name} ({org.slug})")
    return org


async def _ensure_user(session, org: Organisation, email: str, password: str,
                       role: str) -> User:
    existing = (await session.execute(
        select(User).where(User.email == email.lower())
    )).scalar_one_or_none()
    if existing:
        return existing
    user = User(
        organisation_id=org.id, email=email.lower(),
        password_hash=hash_password(password), role=role,
    )
    session.add(user)
    await session.flush()
    print(f"  user {email} ({role})")
    return user


async def _ensure_registry(session) -> None:
    for module in MODULES:
        existing = (await session.execute(
            select(ModelRegistry).where(ModelRegistry.module == module)
        )).scalars().all()
        if existing:
            continue
        session.add(ModelRegistry(
            module=module,
            name="classical-cv",
            version="0.1.0",
            backend="classical_cv",
            active=True,
            artifact_uri=None,
            metrics_json={
                "status": "placeholder",
                "validated": False,
                "note": "Rule-based surface descriptors. No training data, no "
                        "measured sensitivity or specificity. Replace with a "
                        "validated model before any clinical evaluation.",
            },
        ))
        print(f"  model_registry: {module} -> classical-cv 0.1.0 (active)")


async def _ensure_patients(session, org: Organisation,
                           creator: User) -> list[Patient]:
    out = []
    for ref, dob_year, sex, tone in DEMO_PATIENTS:
        patient = (await session.execute(
            select(Patient).where(Patient.external_ref == ref)
        )).scalar_one_or_none()
        if patient is None:
            patient = Patient(
                organisation_id=org.id,
                external_ref=ref, dob_year=dob_year, sex=sex,
                skin_tone_monk=tone, consent_flag=True, created_by=creator.id,
            )
            session.add(patient)
            await session.flush()
            print(f"  patient {ref} (Monk {tone}, consent recorded)")
        out.append(patient)
    return out


def _write_sample_files() -> None:
    SAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    for sample in SAMPLES:
        path = SAMPLES_DIR / f"{sample.name}.png"
        path.write_bytes(png_bytes(sample.name))
    (SAMPLES_DIR / "README.md").write_text(
        "# Synthetic sample images\n\n"
        "Generated by `app/sample_data.py` from drawing primitives. No real "
        "patient data is involved. They exist to exercise the pipeline and the "
        "UI, and are **not** evidence that the placeholder model works on real "
        "skin.\n\n"
        + "\n".join(
            f"- `{s.name}.png` — module `{s.module}`, expected grade "
            f"`{s.expected_grade or 'quality rejection'}`. {s.description}"
            for s in SAMPLES
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"  wrote {len(SAMPLES)} sample images to {SAMPLES_DIR}")


async def _seed_cases(session, clinician: User, patients: list[Patient]) -> None:
    storage = get_storage()
    analysable = [s for s in SAMPLES if s.expected_grade is not None]

    existing = (await session.execute(select(Case))).scalars().first()
    if existing:
        print("  cases already present, skipping demo analyses")
        return

    for idx, sample in enumerate(analysable):
        patient = patients[idx % len(patients)]
        case = Case(
            organisation_id=patient.organisation_id,
            patient_id=patient.id,
            module=sample.module,
            created_by=clinician.id,
            body_site=MODULES[sample.module]["body_sites"][0],
            note=f"Synthetic demo case: {sample.description}",
            status="created",
        )
        session.add(case)
        await session.flush()

        data = png_bytes(sample.name)
        output = execute(AnalysisJob(image_bytes=data, module=sample.module))
        if output.result is None:
            print(f"  {sample.name}: quality gate rejected (expected for "
                  f"quality samples only) — skipped")
            continue

        image_key = build_key(str(case.id), "source", data, "png")
        storage.put(image_key, data, "image/png")
        overlay_key = None
        if output.overlay_png:
            overlay_key = build_key(str(case.id), "overlay", output.overlay_png, "png")
            storage.put(overlay_key, output.overlay_png, "image/png")

        captured_at = dt.datetime.now(dt.timezone.utc)
        image = Image(
            case_id=case.id, storage_key=image_key, content_type="image/png",
            width=output.width, height=output.height, captured_at=captured_at,
            quality_json=output.quality.to_json(),
        )
        session.add(image)
        await session.flush()

        result = output.result
        analysis = Analysis(
            case_id=case.id, image_id=image.id, module=sample.module,
            model_version=result.model_version, backend=result.backend,
            triage_grade=str(result.triage.grade),
            triage_label=result.triage.label,
            confidence=result.triage.confidence,
            next_investigation=result.triage.next_investigation,
            overlay_key=overlay_key,
            rationale_json={
                "rationale": result.triage.rationale,
                "features": result.features,
                "clinical": result.clinical,
                "urgency": result.triage.urgency,
                "routing_target": result.triage.routing_target,
                "summary": build_summary(
                    module=sample.module, patient_ref=patient.external_ref,
                    body_site=case.body_site, result=result,
                    quality=output.quality,
                    captured_at=captured_at.isoformat(timespec="seconds"),
                ),
                "notes": output.notes,
                "descriptions": {l.kind: l.description for l in result.lesions},
            },
        )
        session.add(analysis)
        await session.flush()
        session.add_all([
            Lesion(
                analysis_id=analysis.id, kind=l.kind, area_pct=l.area_pct,
                severity=l.severity,
                bbox_json={"x": l.bbox[0], "y": l.bbox[1],
                           "w": l.bbox[2], "h": l.bbox[3]},
                centroid_json={"x": l.centroid[0], "y": l.centroid[1]},
            )
            for l in result.lesions
        ])
        case.status = "analyzed"
        flag = "OK " if str(result.triage.grade) == sample.expected_grade else "!! "
        print(f"  {flag}case {sample.name}: {result.triage.grade} "
              f"(expected {sample.expected_grade})")


async def seed(reset: bool = False) -> None:
    print(f"QADAM seed — database {settings.database_url.split('@')[-1]}")
    if reset:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.drop_all)
        print("  schema dropped")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with SessionLocal() as session:
        org = await _ensure_org(session)
        admin = await _ensure_user(
            session, org, settings.seed_admin_email,
            settings.seed_admin_password, "admin",
        )
        clinician = await _ensure_user(
            session, org, settings.seed_clinician_email,
            settings.seed_clinician_password, "clinician",
        )
        await _ensure_registry(session)
        patients = await _ensure_patients(session, org, admin)
        await session.flush()
        _write_sample_files()
        await _seed_cases(session, clinician, patients)
        await session.commit()

    print("\nSign in with:")
    print(f"  clinician: {settings.seed_clinician_email} / "
          f"{settings.seed_clinician_password}")
    print(f"  admin:     {settings.seed_admin_email} / "
          f"{settings.seed_admin_password}")
    print("\nNOT A MEDICAL DEVICE — not for clinical use. "
          "Research/decision-support only.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed the QADAM demo database.")
    parser.add_argument("--reset", action="store_true",
                        help="drop and recreate the schema first")
    args = parser.parse_args()
    asyncio.run(seed(reset=args.reset))


if __name__ == "__main__":
    main()
